# Generated by Django 5.0.1 on 2024-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_news_alter_categories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
