# Generated by Django 5.0.1 on 2024-05-04 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_rating_options_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='books_time',
            field=models.DateField(default=datetime.datetime(2024, 5, 4, 16, 37, 10, 85897)),
        ),
    ]
