# Generated by Django 5.0.1 on 2024-01-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_alter_news_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('book_description', models.CharField(max_length=255)),
                ('books_time', models.DateField()),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
