# Generated by Django 4.2.10 on 2024-05-10 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_books_books_time_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='report_content',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='books_time',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 9, 59, 28, 219299)),
        ),
    ]
