# Generated by Django 5.0.1 on 2024-05-10 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_books_books_time_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='report_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='books_time',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 13, 0, 36, 976713)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_theme',
            field=models.CharField(max_length=40),
        ),
    ]
