# Generated by Django 5.0.1 on 2024-01-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_name', models.TextField()),
                ('part_content', models.TextField()),
                ('book_id', models.BigIntegerField()),
            ],
        ),
    ]
