# Generated by Django 5.0.1 on 2024-02-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_books_author_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre_name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='parts',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='bookapp.books'),
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(to='bookapp.genres'),
        ),
    ]
