# Generated by Django 5.0.1 on 2024-05-16 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_reports_report_content_alter_books_books_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='books_time',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 21, 9, 0, 364308)),
        ),
    ]
