# Generated by Django 5.0.1 on 2024-02-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
