# Generated by Django 5.0.1 on 2024-01-30 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_alter_parts_part_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='part_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
