# Generated by Django 5.0.1 on 2024-02-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_genres_alter_parts_book_books_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AddField(
            model_name='books',
            name='book_status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='bookapp.genres'),
        ),
    ]
