# Generated by Django 5.0.1 on 2024-01-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_alter_parts_part_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.RemoveField(
            model_name='parts',
            name='book_id',
        ),
        migrations.AddField(
            model_name='parts',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.books'),
        ),
    ]
