# Generated by Django 5.0.1 on 2024-05-19 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_user_is_blocked_alter_books_books_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='decision',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='books_time',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 18, 46, 8, 822473)),
        ),
    ]
